"""CLI command specifications."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class CommandSpec:
    group: str
    command: str
    method: str
    description: str
    requires_celex: bool = False
    requires_since: bool = False
    has_since: bool = False
    has_resource_type: bool = False
    has_country: bool = False
    has_lang: bool = False
    has_direction: bool = False
    has_limit_offset: bool = False
    has_format: bool = False
    list_arg_name: str | None = None
    scalar_arg_name: str | None = None


COMMANDS: list[CommandSpec] = [
    CommandSpec(
        "lookup",
        "resolve-celex",
        "resolve_celex",
        description="Resolve a CELEX identifier to the canonical CELLAR work reference.",
        requires_celex=True,
    ),
    CommandSpec(
        "lookup",
        "get-act",
        "get_act",
        description="Fetch the main metadata card for one act when you need title, type, dates, and institutions.",
        requires_celex=True,
        has_lang=True,
    ),
    CommandSpec(
        "lookup",
        "get-eurovoc",
        "get_eurovoc",
        description="List the EuroVoc concepts linked to one act.",
        requires_celex=True,
        has_limit_offset=True,
    ),
    CommandSpec(
        "lookup",
        "get-subject-matter",
        "get_subject_matter",
        description="List the subject-matter concepts linked to one act.",
        requires_celex=True,
        has_limit_offset=True,
    ),
    CommandSpec(
        "lookup",
        "get-legal-basis",
        "get_legal_basis",
        description="Inspect treaty basis and based-on relations, including delegated-act to base-act reverse lookup.",
        requires_celex=True,
        has_limit_offset=True,
    ),
    CommandSpec(
        "lookup",
        "get-directory-codes",
        "get_directory_codes",
        description="List directory-code concepts assigned to one act.",
        requires_celex=True,
        has_limit_offset=True,
    ),
    CommandSpec(
        "lookup",
        "get-expressions",
        "get_expressions",
        description="List language expressions and versions available for one act.",
        requires_celex=True,
        has_limit_offset=True,
    ),
    CommandSpec(
        "relations",
        "get-amendments",
        "get_amendments",
        description="Show amendment relations affecting or issued by the act.",
        requires_celex=True,
        has_since=True,
        has_resource_type=True,
        has_lang=True,
        has_direction=True,
        has_limit_offset=True,
    ),
    CommandSpec(
        "relations",
        "get-repeals",
        "get_repeals",
        description="Show explicit and implicit repeal relations affecting or issued by the act.",
        requires_celex=True,
        has_since=True,
        has_resource_type=True,
        has_lang=True,
        has_direction=True,
        has_limit_offset=True,
    ),
    CommandSpec(
        "relations",
        "get-citations",
        "get_citations",
        description="Show works that cite the act when you need broad legal and non-legal references.",
        requires_celex=True,
        has_since=True,
        has_resource_type=True,
        has_lang=True,
        has_direction=True,
        has_limit_offset=True,
    ),
    CommandSpec(
        "relations",
        "get-based-on-acts",
        "get_based_on_acts",
        description="Show the broad incoming based-on bucket for acts and documents derived from the act.",
        requires_celex=True,
        has_since=True,
        has_resource_type=True,
        has_lang=True,
        has_limit_offset=True,
    ),
    CommandSpec(
        "relations",
        "get-completing-acts",
        "get_completing_acts",
        description="Show the narrower completes relation for acts that supplement or complete the act.",
        requires_celex=True,
        has_since=True,
        has_resource_type=True,
        has_lang=True,
        has_limit_offset=True,
    ),
    CommandSpec(
        "relations",
        "get-proposals-to-change",
        "get_proposals_to_change",
        description="Show proposal acts that may amend, repeal, recast, or otherwise change the act.",
        requires_celex=True,
        has_since=True,
        has_resource_type=True,
        has_lang=True,
        has_limit_offset=True,
    ),
    CommandSpec(
        "relations",
        "get-adopted-act",
        "get_adopted_act",
        description="Show adopted acts linked to the act from proposal or precursor workflows.",
        requires_celex=True,
        has_since=True,
        has_resource_type=True,
        has_lang=True,
        has_limit_offset=True,
    ),
    CommandSpec(
        "relations",
        "get-related-works",
        "get_related_works",
        description="Show generic related-work links when no narrower relation command fits.",
        requires_celex=True,
        has_since=True,
        has_resource_type=True,
        has_lang=True,
        has_direction=True,
        has_limit_offset=True,
    ),
    CommandSpec(
        "relations",
        "get-other-relations",
        "get_other_relations",
        description="Inspect sparse catch-all legal relations such as suspend, defer, obsolete, or influence.",
        requires_celex=True,
        has_since=True,
        has_resource_type=True,
        has_lang=True,
        has_direction=True,
        has_limit_offset=True,
    ),
    CommandSpec(
        "relations",
        "get-article-annotations",
        "get_article_annotations",
        description="Retrieve OWL-style article annotations with article, paragraph, point, and legal-basis qualifiers.",
        requires_celex=True,
        has_limit_offset=True,
    ),
    CommandSpec(
        "lifecycle",
        "get-consolidated-versions",
        "get_consolidated_versions",
        description="List consolidated-text relations and aliases linked to the act.",
        requires_celex=True,
        has_since=True,
        has_resource_type=True,
        has_lang=True,
        has_limit_offset=True,
    ),
    CommandSpec(
        "lifecycle",
        "get-corrigenda",
        "get_corrigenda",
        description="List corrigenda linked to the act, defaulting to corrigendum-type rows.",
        requires_celex=True,
        has_since=True,
        has_resource_type=True,
        has_lang=True,
        has_limit_offset=True,
    ),
    CommandSpec(
        "lifecycle",
        "get-nims",
        "get_nims",
        description="List grouped national implementing measures for a directive or other implementation-driven act.",
        requires_celex=True,
        has_since=True,
        has_resource_type=True,
        has_lang=True,
        has_limit_offset=True,
    ),
    CommandSpec(
        "lifecycle",
        "get-dossier",
        "get_dossier",
        description="List other documents in the act's dossier when you need the dossier feed rather than a timeline.",
        requires_celex=True,
        has_lang=True,
        has_limit_offset=True,
    ),
    CommandSpec(
        "lifecycle",
        "get-opinions",
        "get_opinions",
        description="Show opinion-like and influence-like rows, most useful on proposals and legislative packages.",
        requires_celex=True,
        has_since=True,
        has_lang=True,
        has_limit_offset=True,
    ),
    CommandSpec(
        "lifecycle",
        "get-deadlines",
        "get_deadlines",
        description="List deadline and date-fact rows attached to the act itself.",
        requires_celex=True,
        has_limit_offset=True,
    ),
    CommandSpec(
        "case-law",
        "get-cjeu-judgments",
        "get_cjeu_judgments",
        description="List CJEU judgments interpreting the act.",
        requires_celex=True,
        has_since=True,
        has_resource_type=True,
        has_lang=True,
        has_limit_offset=True,
    ),
    CommandSpec(
        "case-law",
        "get-ag-opinions",
        "get_ag_opinions",
        description="List Advocate General opinions linked to the act as a relation feed rather than a case-law payload.",
        requires_celex=True,
        has_since=True,
        has_lang=True,
        has_limit_offset=True,
    ),
    CommandSpec(
        "case-law",
        "get-preliminary-questions",
        "get_preliminary_questions",
        description="List preliminary questions submitted about the act, often with sparse INFO_JUDICIAL metadata.",
        requires_celex=True,
        has_since=True,
        has_resource_type=True,
        has_lang=True,
        has_limit_offset=True,
    ),
    CommandSpec(
        "case-law",
        "get-national-decisions",
        "get_national_decisions",
        description="List national decisions referencing the act by CELEX mention, optionally filtered by country.",
        requires_celex=True,
        has_since=True,
        has_country=True,
        has_lang=True,
        has_limit_offset=True,
    ),
    CommandSpec(
        "search",
        "search-by-eurovoc",
        "search_by_eurovoc",
        description="Find acts by EuroVoc tags after local concept resolution.",
        has_since=True,
        list_arg_name="tags",
        has_resource_type=True,
        has_lang=True,
        has_limit_offset=True,
    ),
    CommandSpec(
        "search",
        "search-by-subject-matter",
        "search_by_subject_matter",
        description="Find acts by subject-matter codes or labels after local concept resolution.",
        has_since=True,
        list_arg_name="codes",
        has_resource_type=True,
        has_lang=True,
        has_limit_offset=True,
    ),
    CommandSpec(
        "search",
        "search-by-title",
        "search_by_title",
        description="Find acts by title keyword with optional type and date filtering.",
        has_since=True,
        scalar_arg_name="keyword",
        has_resource_type=True,
        has_lang=True,
        has_limit_offset=True,
    ),
    CommandSpec(
        "search",
        "search-communications",
        "search_communications",
        description="Find Commission communications by DG when you want policy and preparatory signals rather than legislation.",
        has_since=True,
        scalar_arg_name="dg",
        has_lang=True,
        has_limit_offset=True,
    ),
    CommandSpec(
        "search",
        "find-eurovoc-concept",
        "find_eurovoc_concept",
        description="Search the packaged local EuroVoc index for concepts matching a label.",
        scalar_arg_name="label",
        has_limit_offset=True,
    ),
    CommandSpec(
        "monitoring",
        "new-citations",
        "new_citations",
        description="Monitor new citation rows for the act since a required lower date bound.",
        requires_celex=True,
        requires_since=True,
        has_resource_type=True,
        has_lang=True,
        has_limit_offset=True,
    ),
    CommandSpec(
        "monitoring",
        "new-amendments",
        "new_amendments",
        description="Monitor new amendment rows for the act since a required lower date bound.",
        requires_celex=True,
        requires_since=True,
        has_resource_type=True,
        has_lang=True,
        has_limit_offset=True,
    ),
    CommandSpec(
        "monitoring",
        "new-repeals",
        "new_repeals",
        description="Monitor new repeal rows for the act since a required lower date bound.",
        requires_celex=True,
        requires_since=True,
        has_resource_type=True,
        has_lang=True,
        has_limit_offset=True,
    ),
    CommandSpec(
        "monitoring",
        "new-proposals-to-change",
        "new_proposals_to_change",
        description="Monitor new proposals that may change the act since a required lower date bound.",
        requires_celex=True,
        requires_since=True,
        has_resource_type=True,
        has_lang=True,
        has_limit_offset=True,
    ),
    CommandSpec(
        "monitoring",
        "new-based-on-acts",
        "new_based_on_acts",
        description="Monitor new acts and documents derived from the act via the broad based-on relation.",
        requires_celex=True,
        requires_since=True,
        has_resource_type=True,
        has_lang=True,
        has_limit_offset=True,
    ),
    CommandSpec(
        "monitoring",
        "new-case-law",
        "new_case_law",
        description="Monitor new CJEU case-law items linked to the act since a required lower date bound.",
        requires_celex=True,
        requires_since=True,
        has_resource_type=True,
        has_lang=True,
        has_limit_offset=True,
    ),
    CommandSpec(
        "monitoring",
        "new-preliminary-questions",
        "new_preliminary_questions",
        description="Monitor new preliminary questions linked to the act since a required lower date bound.",
        requires_celex=True,
        requires_since=True,
        has_resource_type=True,
        has_lang=True,
        has_limit_offset=True,
    ),
    CommandSpec(
        "monitoring",
        "new-corrigenda",
        "new_corrigenda",
        description="Monitor new corrigenda linked to the act since a required lower date bound.",
        requires_celex=True,
        requires_since=True,
        has_resource_type=True,
        has_lang=True,
        has_limit_offset=True,
    ),
    CommandSpec(
        "monitoring",
        "new-consolidated",
        "new_consolidated",
        description="Monitor new consolidated-text relations linked to the act since a required lower date bound.",
        requires_celex=True,
        requires_since=True,
        has_resource_type=True,
        has_lang=True,
        has_limit_offset=True,
    ),
    CommandSpec(
        "monitoring",
        "new-nims",
        "new_nims",
        description="Monitor new grouped national implementing measures since a required lower date bound.",
        requires_celex=True,
        requires_since=True,
        has_resource_type=True,
        has_lang=True,
        has_limit_offset=True,
    ),
    CommandSpec(
        "monitoring",
        "new-by-eurovoc",
        "new_by_eurovoc",
        description="Monitor new acts by EuroVoc tags since a required lower date bound.",
        requires_since=True,
        list_arg_name="tags",
        has_resource_type=True,
        has_lang=True,
        has_limit_offset=True,
    ),
    CommandSpec(
        "download",
        "get-text",
        "get_text",
        description="Download the full text of an act in the requested format and language.",
        requires_celex=True,
        has_lang=True,
        has_format=True,
    ),
    CommandSpec(
        "download",
        "get-summary",
        "get_summary",
        description="Download the official summary for an act in the requested language.",
        requires_celex=True,
        has_lang=True,
    ),
]
